language: java
jdk: oraclejdk8
os: linux

notifications:
  email:
    recipients:
        - atmosphere@musala.com
    
cache:
    directories:
        - $HOME/.gradle

before_script:
    - git fetch
    - chmod +x gradlew

script:
    - ./gradlew build publishToMavenLocal

